#!/bin/sh
# Author: Jan Keith Darunday <github@jkcdarunday.mozmail.com>

SINKS=$(pactl list short sinks | grep -v easyeffects)
SINK_COUNT=$(echo "$SINKS" | wc -l)

DEFAULT_SINK=$(pactl info | sed -En 's/Default Sink: (.*)/\1/p')
DEFAULT_SINK_INDEX=$(echo "$SINKS" | grep -n "$DEFAULT_SINK" | grep -Eo '^[0-9]+')

NEW_SINK_INDEX=$((DEFAULT_SINK_INDEX % $SINK_COUNT + 1))
NEW_SINK=$(echo "$SINKS" | sed "${NEW_SINK_INDEX}q;d" | awk '{ print $2 }')

# Set next sink as the default sink
pactl set-default-sink "$NEW_SINK"

# User convinience
# notify-send "Audioausgabe gewechselt"
aplay ~/.local/share/confirm_sound.wav

# Forward all playing audio (sink inputs) to the new sink (Uncomment if your system does not automatically do this)
#SINK_INPUTS=($(pactl list short sink-inputs | grep -Eo '^[0-9]+'))
#for SINK_INPUT in ${SINK_INPUTS[*]}; do pactl move-sink-input $SINK_INPUT $NEW_SINK; done



# sink="$(pactl info | grep Sink)"
# if [ "$sink" = "Default Sink: alsa_output.pci-0000_0c_00.4.pro-output-0" ]
# then
#   echo "$sink"
#   pactl set-default-sink alsa_output.pci-0000_06_00.1.hdmi-stereo-extra4
#   notify-send "Audioausgabe auf Lautsprecher gewechselt"
#   aplay ~/.local/share/confirm_sound.wav
# else
#   echo "$sink"
#   pactl set-default-sink alsa_output.pci-0000_0c_00.4.pro-output-0
#   notify-send "Audioausgabe auf Kopfhörer gewechselt"
#   aplay ~/.local/share/confirm_sound.wav
# fi
