#!/bin/bash

sysappimagepath="/opt/AppImage"
usrappimagepath="$HOME/.local/AppImage"
sysexpath="/opt/bin"
usrexpath="$HOME/.local/bin"
name="basename $2"
tmpfile="/tmp/$(shuf --random-source=/dev/random -i 100000-999999 -n1).desktop"
sysdesktop="/usr/local/share/applications"
usrdesktop="$HOME/.local/share/applications"
touch $tmpfile

while getopts :us: flag
do
	case "${flag}" in
		u)
			usrinstall();;
		s)
			sysinstall();;

	esac
done

crdesktopfile() {
	read -p "Enter Name: " dfname
	read -p "Enter GenericName: " dfgen
	echo "List of Categories: AudioVideo;Audio;Video;Development;Education;Game;Graphics;Network;Office;Science;Settings;System;Utility"
	read -p "Enter Categories: " dfcat
	echo "to lazy to implement auto execpath, pls enter yourself"
	read -p "Enter Exec: " dfexec
	read -p "Enter Categories: " dfcat
	icons=$(find /usr/share/icons /home/$USER/.icons /usr/local/share/icons \
	-type f \( -name "*.png" -o -name "*.svg" \) | awk -F/ '{print $NF}' | sort -u)
	icon_list=$(echo "$icons" | awk '{print $0 "!" $0}')
	choosen=$(echo "$icon_list" | yad --list --title="Choose an Icon" \
	--width=600 --height=400 \
	--search-column=2 \
	--column="Icon":IMG --column="Name" \
	--separator="" --print-column=2)
	dficon="$(echo $choosen | awk -F '\\.' '{print $1}')"
	echo $dficon
	cat >> /tmp/$tmpfile.desktop << EOF
	[Desktop Entry]
	Name=$appname
	GenericName=$dfgen
	Exec=$dfexec
	Icon=$dficon
	Terminal=false
	Type=Application
	Categories=$dfcat
	StartupNotify=false

EOF
}

usrinstall() {
	cp "$2" "$usrappimagepath"
	ln -s "$usrappimagepath"/"$name" "$usrexpath"
	crdesktopfile()
	mv "$tmpfile" "$usrdesktop"/"$name".desktop
}

sysinstall() {
	cp "$2" "$sysappimagepath"
	chown root:root "$sysappimagepath"/"$name"
	chmod 755 "$sysappimagepath"/"$name"
	crdesktopfile()
	ln -s "$sysappimagepath"/"$name" "$sysexpath"
}
