#!/bin/bash

phoneip="192.168.178.12"
adbport="5555"
sshport="8022"

function main ()
{
	exec="$(printf "screenmirror\nadb\nssh\nsftp\nsendfile\nring" | fzy)"
	"$exec"
}

function screenmirror ()
{
	sh -c "adb connect '$phoneip':'$adbport' && scrcpy || scrcpy"
}

function adb ()
{
	sh -c "adb connect '$phoneip':'$adbport' && adb shell || adb shell"
}

function ssh ()
{
	sh -c "ssh -p '$sshport' '$phoneip'"

}

function sftp ()
{
	sh -c "sftp -P '$sshport' '$phoneip'"

}

function sendfile ()
{
	method=$(printf "zenity\nfzf" | fzy)
	case "$method" in
		zenity) file="$(zenity --file-selection)"
			;;
		fzf) FZF_DEFAULT_COMMAND='fd -H . "$HOME"' file="$(fzf-tmux)"
			;;
		*) exit
			;;
	esac
	kdeconnect-cli -n "Pixel 4a" --share "$file"
}

function ring ()
{
	kdeconnect-cli -n "Pixel 4a" --ring
}

main
