#!/bin/bash

function main ()
{
	exec="$(printf "screenmirror\nadb\nssh\nsftp\nsendfile\nring" | fzy)"
	"$exec"
}

function screenmirror ()
{
	scrcpy
}

function adb ()
{
	sh -c "adb connect 192.168.178.12:5555"
	sh -c "adb shell"
}

function ssh ()
{
	sh -c "ssh -p 8022 192.168.178.12"

}

function sftp ()
{
	sh -c "sftp -P 8022 192.168.178.12"

}

function sendfile ()
{
	method=$(printf "zenity\nfzf" | fzy)
	case "$method" in
		zenity) file="$(zenity --file-selection)"
			;;
		fzf) FZF_DEFAULT_COMMAND='fd -H . "$HOME"' file="$(fzf-tmux)"
			;;
		*) exit
			;;
	esac
	kdeconnect-cli -n "Pixel 4a" --share "$file"
}

function ring ()
{
	kdeconnect-cli -n "Pixel 4a" --ring
}

main
