#!/bin/sh
while true; do
  if [ "$(pactl list short sinks | wc -l)" -lt 2 ]; then
    echo "pipewire: not all sinks loaded - restarting wireplumber..."
    systemctl --user restart wireplumber;
    echo "pipewire: rstarting wireplumbe successfull."
  else
    echo "pipewire: all sinks loaded."
  fi
  sleep 5;
done
