#!/bin/sh
#if the output of $window isn't "Terminal" for you, adjust accordingly
window="$(xdotool getactivewindow getwindowname | awk '{print $1}')"

plus() {
  if [ "$window" = "Terminal" ]; then
      xdotool key ctrl+shift+t
  else
      xdotool key ctrl+t
  fi
}

minus() {
  if [ "$window" = "Terminal" ]; then
      xdotool key ctrl+shift+w
  else
      xdotool key ctrl+w
  fi
}

"$@"
