#!/bin/bash

# a fzf list of all active tmux sessions and option to create new one

sessions="$(tmux ls | awk -F: '{print $1}')"
session="$(echo "$sessions" | fzy)"

if [[ "$sessions" = *"$session"* ]]; then
	tmux attach -d -t "$session"
else
	dir="$(printf ".\n%s" "$(find ~ -type d)" | fzy)"
	tmux new -s "$session" -c "$dir"

fi
