#!/bin/sh

echo "Updating system..."
sudo apt update;
sudo apt upgrade;
printf "\n"
echo "Updating Flatpaks..."
flatpak update
printf "\n"
echo "Updating neovim-plugins..."
nvim --headless '+NvChadUpdate' +qa
printf "\n"
echo "Updating tmux-plugins..."
~/.config/tmux/plugins/tpm/bin/update_plugins all
