#!/bin/sh

echo "Updating system..."
sudo nala upgrade --update;
printf "\n"
echo "Updating neovim-plugins..."
nvim --headless "+Lazy! sync" +qa
printf "\n"
echo "Updating tmux-plugins..."
~/.config/tmux/plugins/tpm/bin/update_plugins all
